# Generated by Django 3.2.7 on 2021-09-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deepthought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deepthought_text', models.CharField(max_length=200)),
                ('deepthought_title', models.CharField(max_length=200)),
            ],
        ),
    ]
